Bei 10 setup code coverage with jest
korapay/Foodies-Haven pull request #11
Opened 2023-07-13 11:01 UTC by LucianaDera

WHY THIS PR?

We need a test to fail if code coverage does not reach the required threshold of 60% on all metrics.

WHAT DOES THE PR DO?
- It can help detect bugs early in the development process.
- Serves as a metric for assessing the quality of the codebase.
- test will fail if it does not reach the required threshold.

HOW CAN THIS PR BE TESTED?
- Configure test coverage with jest.
- Run test.

THINGS YOU MAY WANT THE REVIEWER TO NOTE.
N/A

2023-07-13 12:07 UTC, LordUche requested changes

2023-07-13 12:07 UTC, LordUche commented on .hound.yml
> +  fail_on_violations: true
```suggestion
fail_on_violations: true
```

2023-07-13 14:40 UTC, RICHYDOS commented on .jest.config.js
Is the file name meant to be ".jest.config.js" or "jest.config.js"

2023-07-13 16:23 UTC, LordUche requested changes

2023-07-13 23:04 UTC, hizikex commented
Resolve the branch conflicts.

2023-07-14 10:38 UTC, hizikex approved these changes

2023-07-14 10:39 UTC, RICHYDOS approved these changes
Well Done

2023-07-14 11:35 UTC, LordUche commented
@LucianaDera Please add `coverage/` to `.gitignore`

2023-07-14 11:48 UTC, LordUche requested changes
Great job 👍
Please pull the latest changes on staging and resolve all conflicts.

2023-07-14 11:48 UTC, LordUche commented on tsconfig.json
> +  },
These changes have nothing to do with the task

2023-07-14 11:48 UTC, LordUche commented on package.json
> +    "jest-cli": "^29.6.1",
Why do you need this package?

2023-07-17 11:06 UTC, LordUche approved these changes

2023-07-17 11:06 UTC, merged