BEI-11: setup ci/cd with github actions
korapay/Foodies-Haven pull request #12
Opened 2023-07-13 23:17 UTC by LucianaDera

WHY THIS PR?
To make it easy to set up and manage CI/CD pipelines directly within our repository.

WHAT DOES THIS PR DO?
-  It allows you to automatically build, test, and validate your code whenever changes are pushed.

HOW CAN THIS PR BE TESTED?
- Create test workflow.
-  Trigger the test workflows by making changes to the test.

THINGS YOU MAY WANT THE REVIEWER TO NOTE.
N/A

2023-07-14 05:56 UTC, hizikex commented
Please resolve the conflicts on this files.

2023-07-14 09:43 UTC, LordUche commented
@LucianaDera you should branch out of the default branch which is `staging`.

2023-07-14 10:41 UTC, RICHYDOS approved these changes

2023-07-17 10:06 UTC, hizikex approved these changes

2023-07-17 11:09 UTC, LordUche commented
Great work @LucianaDera 👍
Please resolve the merge conflicts

2023-07-19 09:34 UTC, LordUche requested changes

2023-07-19 09:34 UTC, LordUche commented on tsconfig.json
>    }
```suggestion
    "strict": true,
    "noUnusedLocals": true,
    "noImplicitReturns": true,
    "skipLibCheck": true
  }
}
```

2023-07-19 14:13 UTC, LordUche requested changes

2023-07-19 14:13 UTC, LordUche commented on superLinter.yml
> +          node-version: 14
```suggestion
          node-version: 18
```
One more change

2023-07-19 14:13 UTC, LordUche commented on superLinter.yml
> +      - main
```suggestion
      - staging
```

2023-07-19 14:13 UTC, LordUche commented on superLinter.yml
> +      - main
```suggestion
      - staging
```

2023-07-20 13:02 UTC, merged