BEI-20: Create the users table
korapay/Foodies-Haven pull request #15
Opened 2023-07-21 18:07 UTC by hizikex

WHY THIS PR?
- We need a model for users to be uniquely identified and authenticated.

WHAT DOES THIS PR DO?
- It creates a model for users to be individually identified and be authenticated.
- It creates a secured and organized approach to managing user-related data.

HOW CAN THIS PR BE TESTED?
-When a datatype does not correspond to the given datatype of a field.

THINGS YOU MAY WANT THE REVIEWER TO NOTE.
N/A

2023-07-22 21:38 UTC, LucianaDera requested changes
Are they any reason we're having four model folders, and is the interface in use?

2023-07-22 21:38 UTC, LucianaDera commented on package.json
Any reason why we installed express

2023-07-23 03:10 UTC, hizikex commented on package.json
No. It is removed.

2023-07-23 13:40 UTC, LucianaDera approved these changes

2023-07-23 23:41 UTC, mushkaa commented on src/core/database/config/config.json
> +{
Let's use the dynamic config setup [here](https://sequelize.org/docs/v6/other-topics/migrations/#dynamic-configuration) instead so we can pull the information from the env file instead of hard coding it here https://sequelize.org/docs/v6/other-topics/migrations/#dynamic-configuration

2023-07-23 23:43 UTC, mushkaa commented on src/core/database/migrations/20230721170913-create-users.js
> +      },
We should have unique constraints on these fields to guarantee that we don't have duplicate records of the same username/email

2023-07-23 23:44 UTC, mushkaa commented on src/core/database/models/index.js
> +  sequelize = new Sequelize(process.env[config.use_env_variable], config);
Please share what the value od `process.env[config.use_env_variable]` would look like

2023-07-23 23:45 UTC, mushkaa commented on src/core/database/migrations/20230721170913-create-users.js
> +      token: {
What information do we intend to save here?

2023-07-23 23:47 UTC, mushkaa commented on src/core/database/models/users.js
I noticed that we have two model files  ([typescript](https://github.com/korapay/Foodies-Haven/pull/15/files#diff-20512c3b0929386ee5fc665e0c6f43555c9e20f63e0d328066ea9ad3f9169d2a) and [javascript](https://github.com/korapay/Foodies-Haven/pull/15/files#diff-cdc47f58fdc1e73cc88614ad34c6c27e59705779eb9c6928311598d96350745f)). What's the reason for having it like that?

2023-07-24 07:37 UTC, hizikex commented on src/core/database/migrations/20230721170913-create-users.js
> +      token: {
the users password and the generated token.

2023-07-24 07:52 UTC, hizikex commented on src/core/database/models/index.js
> +  sequelize = new Sequelize(process.env[config.use_env_variable], config);
MY_SQL_DB=string
MY_SQL_USER=string
MY_SQL_PASS=string
MY_SQL_HOST='127.0.0.1'

2023-07-24 09:45 UTC, hizikex commented on src/core/database/models/users.js
Do you suggest I remove the typescript model file and the interface file for now?

2023-07-24 12:03 UTC, mushkaa commented on src/core/database/config/config.js
> +    username: process.env.MY_SQL_USER || 'root',
MYSQL is a single word. Let's also update the name in the other places
```suggestion
    username: process.env.MYSQL_USER || 'root',
```

2023-07-24 12:24 UTC, RICHYDOS approved these changes

2023-07-25 12:26 UTC, RICHYDOS commented on src/core/database/migrations/20230725103704-create-users.js
> +      bio: {
"bio" & "image" should have 'allowNull' set to true since they are optional fields

2023-07-25 12:58 UTC, RICHYDOS approved these changes

2023-07-25 15:56 UTC, merged