BEI-26: Create the followers table
korapay/Foodies-Haven pull request #16
Opened 2023-07-26 11:32 UTC by hizikex

#### WHY THIS PR?
We need a model for users to be able to follow one another.

#### WHAT DOES THIS PR DO?
It creates a model for users to be able to follow and unfollow one another.

#### HOW CAN THIS PR BE TESTED?
N/A

#### THINGS YOU MAY WANT THE REVIEWER TO NOTE.
N/A

2023-07-26 12:49 UTC, LucianaDera requested changes

2023-07-26 12:49 UTC, LucianaDera commented on src/core/database/migrations/20230726112251-create-followers.js
> +};
can you add an extra line

2023-07-26 12:51 UTC, hizikex commented on src/core/database/migrations/20230726112251-create-followers.js
> +};
Okay

2023-07-26 13:23 UTC, RICHYDOS requested changes

2023-07-26 13:23 UTC, RICHYDOS commented on src/core/database/migrations/20230726112251-create-followers.js
> +      },
You can't have two primary keys in one table

2023-07-26 14:18 UTC, hizikex commented on src/core/database/migrations/20230726112251-create-followers.js
> +      },
Are you sure about this.

2023-07-26 14:44 UTC, RICHYDOS commented on src/core/database/models/followers.ts
> +        allowNull: true
Shouldn't they both be of type "Integer" to conform with what is in the migrations file?
Then as primary keys I don't think they can be Null

2023-07-27 07:13 UTC, LucianaDera requested changes

2023-07-27 07:13 UTC, LucianaDera commented on src/core/database/models/users.ts
> +      as: 'followees',
please correct the spelling... 

as:"followers"

2023-07-27 07:17 UTC, hizikex commented on src/core/database/models/users.ts
> +      as: 'followees',
We have followers and followees...
Line 49 is meant to be followees not followers

2023-07-27 07:40 UTC, RICHYDOS approved these changes

2023-07-27 07:49 UTC, LucianaDera commented on src/core/database/models/users.ts
> +      as: 'followees',
following might sound better

2023-07-27 08:36 UTC, LucianaDera approved these changes

2023-07-27 13:32 UTC, hizikex commented on src/core/database/migrations/20230726112251-create-followers.js
> +      },
Okay

2023-07-27 14:56 UTC, closed without merging