BEI-10: Create the users table
korapay/Foodies-Haven pull request #17
Opened 2023-07-27 13:38 UTC by hizikex

#### WHY THIS PR?
We need a model for users to be uniquely identified and authenticated.

#### WHAT DOES THIS PR DO?
It creates a model for users to be individually identified and be authenticated.
It creates a secured and organized approach to managing user-related data.

#### HOW CAN THIS PR BE TESTED?
-When a datatype does not correspond to the given datatype of a field.

#### THINGS YOU MAY WANT THE REVIEWER TO NOTE.
N/A

2023-07-27 13:52 UTC, RICHYDOS requested changes
Well Done!

2023-07-27 13:52 UTC, RICHYDOS commented on src/core/database/sequelize.ts
> +// });
If commented code is not needed delete it.

2023-07-27 13:52 UTC, RICHYDOS commented on src/core/interfaces/user.ts
> +    image: string;
Make these two optional to conform with the models and migration files

2023-07-27 13:52 UTC, RICHYDOS commented on src/core/models/users.ts
> +  declare image: string;
Same thing here regarding optional when creating a user

2023-07-27 13:56 UTC, hizikex commented on src/core/database/sequelize.ts
> +// });
Thanks

2023-07-27 14:38 UTC, RICHYDOS approved these changes

2023-07-27 16:07 UTC, LucianaDera approved these changes

2023-07-28 06:16 UTC, mushkaa approved these changes

2023-07-28 06:17 UTC, merged