BEI-26: Create the followers table
korapay/Foodies-Haven pull request #18
Opened 2023-07-27 15:42 UTC by hizikex

WHY THIS PR?
We need a model for users to be able to follow one another.

WHAT DOES THIS PR DO?
It creates a model for users to be able to follow and unfollow one another.

HOW CAN THIS PR BE TESTED?
N/A

THINGS YOU MAY WANT THE REVIEWER TO NOTE.
N/A

2023-07-28 07:07 UTC, RICHYDOS approved these changes

2023-07-28 14:12 UTC, norb-c commented on src/core/models/followers.js
Why is model created and different from the rest.

2023-07-28 14:12 UTC, norb-c commented on src/core/database/seeders/20230727141300-users.js
> +    Example:
Does this need to be here

2023-07-28 14:12 UTC, norb-c commented
Please can we fix the errors
https://github.com/korapay/Foodies-Haven/pull/18#pullrequestreview-1550173012

2023-07-28 17:15 UTC, hizikex commented on src/core/database/migrations/20230727142635-create-users.js
> +      image: {
url image.

2023-07-28 17:15 UTC, hizikex commented on src/core/database/migrations/20230727142635-create-users.js
> +};
done

2023-07-28 17:15 UTC, hizikex commented on src/core/database/migrations/20230727153602-create-followers.js
> +};
done

2023-07-28 17:16 UTC, hizikex commented on src/core/models/followers.js
It's deleted now.

2023-07-28 17:17 UTC, hizikex commented on src/core/database/seeders/20230727141300-users.js
> +    Example:
I don't know. I just know it's not effecting anything.
So I have removed it

2023-07-28 21:42 UTC, mushkaa requested changes

2023-07-28 21:42 UTC, mushkaa commented on src/core/config/config.js
Since this file only contains database config, how about we name it `database.js`?

2023-07-28 21:42 UTC, mushkaa commented on src/core/database/migrations/20230727153602-create-followers.js
> +      },
Let's add a composite unique index for `follower_id` and `followee_id` since the expectation is that the record should unique

2023-07-28 21:42 UTC, mushkaa commented on src/core/models/followers.ts
> +// Define the Sequelize attributes and configurations for the User model
What's the purpose of this comment? Looks like it's also incorrect

2023-07-29 02:46 UTC, hizikex commented on src/core/config/config.js
Okay

2023-07-29 02:46 UTC, hizikex commented on src/core/database/migrations/20230727153602-create-followers.js
> +      },
Okay

2023-07-29 07:24 UTC, LucianaDera commented
please can you resolve this conflict

2023-07-29 16:23 UTC, hizikex commented on src/core/database/migrations/20230727142635-create-users.js
> +      image: {
The data that will be stored is a URL data.

2023-07-29 16:27 UTC, closed without merging