BEI-23: Created the Sequelize migration and model files for the ingre…
korapay/Foodies-Haven pull request #21
Opened 2023-07-28 17:56 UTC by LucianaDera

WHY THIS PR?
We need a Sequelize migration and model files to define the structure for the ingredient table.

WHAT DOES THIS PR DO?
This step allows Sequelize to recognize the model and map the ingredient to the respective database table.

HOW CAN THIS PR BE TESTED?
N/A

THINGS YOU MAY WANT THE REVIEWER TO NOTE.
N/A

2023-07-28 18:20 UTC, hizikex requested changes

2023-07-28 18:20 UTC, hizikex commented on src/core/interfaces/ingredient.ts
> +}
You left each line vacant, can I know why?
Also, there is no space between name and string

2023-07-28 18:20 UTC, hizikex commented on src/core/database/migrations/20230728174324-create_ingredients_table.js
> +};
add a line after line 30

2023-07-28 18:20 UTC, hizikex commented on src/core/database/seeders/20230728174523-ingredient.js
> +    Example:
If this is not effecting anything, you can remove the lines

2023-07-28 18:20 UTC, hizikex commented on src/core/database/seeders/20230728174523-ingredient.js
> +};
add a line after line 24

2023-07-28 18:20 UTC, hizikex commented on src/core/models/ingredient.ts
> +export class Ingredients extends Model<InferAttributes<Ingredients>, InferCreationAttributes<Ingredients, { omit: 'id' }>>implements IngredientAttributes{
you left line 4and 5 vacant. You can removed a line.

2023-07-28 18:20 UTC, hizikex commented on src/core/models/ingredient.ts
> +);
add a line after line 38

2023-07-28 19:03 UTC, LucianaDera commented on src/core/models/ingredient.ts
> +);
There is a line already, else it would flag a red circle.

2023-07-28 19:04 UTC, LucianaDera commented on src/core/database/seeders/20230728174523-ingredient.js
> +};
There is a line already, else it would flag a red circle.

2023-07-28 19:24 UTC, hizikex approved these changes

2023-07-28 21:33 UTC, mushkaa requested changes

2023-07-28 21:33 UTC, mushkaa commented on src/core/database/seeders/20230728174523-ingredient.js
> +     */
```suggestion
  await queryInterface.bulkDelete('ingredients', null, {});
```

2023-07-29 02:38 UTC, hizikex approved these changes

2023-07-29 09:31 UTC, hizikex approved these changes

2023-07-29 09:52 UTC, RICHYDOS commented on src/core/database/migrations/20230728174324-create_ingredients_table.js
> +      },
Shouldn't this field be unique? I'm asking not suggesting.

2023-07-29 09:52 UTC, RICHYDOS commented on src/core/models/ingredient.ts
> +    },
If it should be unique, then add it here too

2023-07-29 20:47 UTC, hizikex approved these changes

2023-07-29 22:30 UTC, RICHYDOS approved these changes

2023-07-31 11:05 UTC, merged