BEI-22: Created the Sequelize migration and model files for the tags …
korapay/Foodies-Haven pull request #22
Opened 2023-07-28 19:39 UTC by LucianaDera

WHY THIS PR?
We need a Sequelize migration and model files to define the structure for the tag table.

WHAT DOES THIS PR DO?
This step allows Sequelize to recognize the model and map the tag to the respective table in the database.

HOW CAN THIS PR BE TESTED?
N/A

THINGS YOU MAY WANT THE REVIEWER TO NOTE.
N/A

2023-07-28 20:18 UTC, RICHYDOS requested changes

2023-07-28 20:18 UTC, RICHYDOS commented on src/core/database/migrations/20230728191333-create_tags_table.js
> +      },
This should have a unique property

2023-07-28 20:18 UTC, RICHYDOS commented on src/core/database/seeders/20230728191412-tags.js
> +      name: "",
Please give this a name since the tag name field cannot be null

2023-07-28 21:20 UTC, hizikex commented on src/core/interfaces/tags.ts
> +}
I am seeing 9 lines of code in this file. Please check

2023-07-28 21:30 UTC, mushkaa requested changes

2023-07-28 21:30 UTC, mushkaa commented on src/core/database/seeders/20230728191412-tags.js
> +   Example:
Let's take this out since it doesn't address any implementation detail

2023-07-28 21:30 UTC, mushkaa commented on src/core/database/seeders/20230728191412-tags.js
> +     */
```suggestion
     await queryInterface.bulkDelete('tags', null, {});
```

2023-07-28 21:30 UTC, mushkaa commented on src/core/interfaces/tags.ts
> +
We can take out the spaces between the interface properties

2023-07-28 21:30 UTC, mushkaa commented on src/core/database/migrations/20230728191333-create_tags_table.js
> +    await queryInterface.dropTable('Ingredients');
```suggestion
    await queryInterface.dropTable('tags');
```

2023-07-28 22:11 UTC, RICHYDOS commented on src/core/database/seeders/20230728191412-tags.js
> +     */
@mushkaa  Since the previous code was surrounded by comments, won't this change actually revert the seeder?

2023-07-29 08:46 UTC, RICHYDOS requested changes

2023-07-29 08:46 UTC, RICHYDOS commented on src/core/database/migrations/20230728191333-create_tags_table.js
> +      },
@LucianaDera you haven't made this change

2023-07-29 08:46 UTC, RICHYDOS commented on src/core/models/tags.ts
> +    },
Please add a unique property here too

2023-07-29 20:42 UTC, hizikex approved these changes

2023-07-29 22:21 UTC, RICHYDOS approved these changes

2023-07-31 11:04 UTC, merged