BEI-29: Create the Sequelize migration and model files for the recipe…
korapay/Foodies-Haven pull request #23
Opened 2023-07-28 22:34 UTC by LucianaDera

WHY THIS PR?
We need a Sequelize migration and model files to define the structure for the recipe ingredient table.

WHAT DOES THIS PR DO?
This step allows Sequelize to recognize the model and map the recipe ingredient to the respective table in the database.

HOW CAN THIS PR BE TESTED?
N/A

THINGS YOU MAY WANT THE REVIEWER TO NOTE.
N/A

2023-07-29 02:27 UTC, hizikex requested changes

2023-07-29 02:27 UTC, hizikex commented on src/core/database/migrations/20230728203815-create_recipe_ingredients_table.js
> +        allowNull: false,
These should be in snake case

2023-07-29 02:27 UTC, hizikex commented on src/core/interfaces/recipe.ingredient.ts
> +}
NO extra line here

2023-07-29 02:27 UTC, hizikex commented on src/core/models/recipe.ingredient.ts
> +});
No extra line

2023-07-29 07:31 UTC, LucianaDera commented on src/core/models/recipe.ingredient.ts
> +});
They are extra lines already

2023-07-31 11:11 UTC, RICHYDOS approved these changes

2023-07-31 11:19 UTC, hizikex approved these changes

2023-07-31 11:20 UTC, merged