BEI-28: Create the Sequelize migration and model files for the recipe…
korapay/Foodies-Haven pull request #24
Opened 2023-07-29 07:48 UTC by LucianaDera

WHY THIS PR?
We need a Sequelize migration and model files to define the structure for the recipe tag table.

WHAT DOES THIS PR DO?
This step allows Sequelize to recognize the model and map the recipe tag to the respective table in the database.

HOW CAN THIS PR BE TESTED?
N/A

THINGS YOU MAY WANT THE REVIEWER TO NOTE.
N/A

2023-07-29 15:05 UTC, hizikex requested changes

2023-07-29 15:05 UTC, hizikex commented on src/core/models/recipe.tag.ts
> +      autoIncrement: true,
This doesn't not need auto_increment, since the id are referenced.

2023-07-29 15:05 UTC, hizikex commented on src/core/models/recipe.tag.ts
> +      autoIncrement: true,
This doesn't not need auto_increment, since the id are referenced.

2023-07-31 11:13 UTC, RICHYDOS commented on src/core/database/migrations/20230728230531-recipe_tags.js
> +        allowNull: false,
I disagree

2023-07-31 12:18 UTC, RICHYDOS approved these changes

2023-08-01 10:40 UTC, RICHYDOS approved these changes

2023-08-01 10:45 UTC, hizikex approved these changes

2023-08-01 14:09 UTC, merged