BEI-26: Create the followers table
korapay/Foodies-Haven pull request #25
Opened 2023-07-29 16:40 UTC by hizikex

#### WHY THIS PR?
We need a followers table where the followers and followees will be tracked.

#### WHAT DOES THIS PR?
This provides a table where followers and followees records can be tracked.

#### HOW CAN THIS BE TESTED
N/A

#### THINGS YOU MAY  WANT THE REVIEWER TO NOTE
N/A

2023-07-29 21:12 UTC, LucianaDera requested changes

2023-07-29 21:12 UTC, LucianaDera commented on src/core/database/migrations/20230729092616-create-followers.js
> +};
please add an extra line.

2023-07-29 21:18 UTC, LucianaDera requested changes

2023-07-29 21:18 UTC, LucianaDera commented on src/core/models/followers.ts
> +// Define the Sequelize attributes and configurations for the User model
please remove the comment since it has no effect

2023-07-29 21:18 UTC, LucianaDera commented on src/core/models/followers.ts
> +// Define the Sequelize attributes and configurations for the User model
please remove the comment since it has no effect

2023-07-29 21:18 UTC, LucianaDera commented on src/core/models/users.ts
> +        allowNull: false
Remove the spaces, so it can be alligned

2023-07-29 21:18 UTC, LucianaDera commented on src/core/models/users.ts
> +        allowNull: false
Remove the spaces, so it can be alligned

2023-07-29 21:18 UTC, LucianaDera commented on src/core/models/followers.ts
> +        unique: true
Is they any reason behind making the follower id unique

2023-07-29 21:18 UTC, LucianaDera commented on src/core/models/followers.ts
> +        unique: true
Is they any reason behind making the follower id unique

2023-07-29 22:39 UTC, RICHYDOS requested changes

2023-07-29 22:39 UTC, RICHYDOS commented on src/core/database/migrations/20230729092616-create-followers.js
> +      },
I agree with @LucianaDera. Don't think they should be unique since the table is just tracking who follows who. 'User A' can follow 'User B' and 'User A' can also follow 'User C'.

2023-07-30 12:03 UTC, RICHYDOS approved these changes

2023-08-01 15:17 UTC, LucianaDera approved these changes

2023-08-01 19:57 UTC, merged