BEI- 25: Create the comments table
korapay/Foodies-Haven pull request #26
Opened 2023-07-29 17:43 UTC by hizikex

WHY THIS PR?
-We need a database to store all comments, who made the comment and on which recipe.
-We want users to review a recipe and be able to comment on it.

WHAT DOES THIS PR?
It creates a table where users can comment what they feel about a recipe.

HOW CAN THIS BE TESTED
N/A

THINGS YOU MAY WANT THE REVIEWER TO NOTE
N/A

2023-07-29 21:34 UTC, LucianaDera requested changes

2023-07-29 21:34 UTC, LucianaDera commented on src/core/database/migrations/20230729164352-create-comments.js
> +/** @type {import('sequelize-cli').Migration} */
Does this comment have any effect on the comment table

2023-07-29 21:34 UTC, LucianaDera commented on src/core/models/comments.ts
> +
please add an extra line

2023-07-29 22:43 UTC, RICHYDOS requested changes
All the stuff relating to the followers table should not be in this pull request

2023-07-29 22:48 UTC, hizikex commented on src/core/database/migrations/20230729164352-create-comments.js
> +/** @type {import('sequelize-cli').Migration} */
I don't think so...
Are you suggesting, I remove it

2023-07-29 22:49 UTC, hizikex commented
> All the stuff relating to the followers table should not be in this pull request

I am hoping that followers will be merged first...

2023-07-30 12:01 UTC, RICHYDOS requested changes

2023-07-30 12:01 UTC, RICHYDOS commented on src/core/models/users.ts
> +import { Follower } from './followers';
Please remove this line because it doesn't have anything to do with this PR

2023-07-31 07:11 UTC, LucianaDera commented on src/core/database/migrations/20230729164352-create-comments.js
> +/** @type {import('sequelize-cli').Migration} */
yes

2023-07-31 07:12 UTC, RICHYDOS approved these changes

2023-07-31 07:17 UTC, LucianaDera requested changes

2023-07-31 07:17 UTC, LucianaDera commented on src/core/database/migrations/20230729164352-create-comments.js
> +/** @type {import('sequelize-cli').Migration} */
yes

2023-08-01 10:44 UTC, LucianaDera approved these changes

2023-08-01 10:48 UTC, merged