BEI-24: Create the steps table
korapay/Foodies-Haven pull request #28
Opened 2023-07-29 22:37 UTC by hizikex

WHY THIS PR?
-We need a database to keep the record of steps to prepare a recipe.

WHAT DOES THIS PR?
-It creates table where steps on how to create a recipe are kept.

HOW CAN THIS BE TESTED
N/A

THINGS YOU MAY WANT THE REVIEWER TO NOTE
N/A

2023-07-30 12:17 UTC, RICHYDOS requested changes

2023-07-30 12:17 UTC, RICHYDOS commented on src/core/database/migrations/20230729221602-create-steps.js
> +  async up(queryInterface, Sequelize) {
Why are there 2 create-steps.js migration files?

2023-07-30 12:17 UTC, RICHYDOS commented on src/core/models/recipe.ts
> +})
Add an extra line here

2023-07-30 12:17 UTC, RICHYDOS commented on src/core/models/steps.ts
> +      },
I have a question. I get why "number" should be unique but putting unique here means that we can't have a particular number appear twice. For example, for "recipe_1" the number field should have a value of 1 appear only once but putting "unique" means that for "recipe_2" we can't have a number field with a value of 1. Is there another way of setting it here or is this something that we should handle in the controllers?

2023-07-31 08:53 UTC, hizikex commented on src/core/models/steps.ts
> +      },
That's true actually

2023-08-01 10:42 UTC, LucianaDera requested changes

2023-08-01 10:42 UTC, LucianaDera commented on src/core/interfaces/step.ts
> +
add an extra line

2023-08-01 10:42 UTC, LucianaDera commented on src/core/models/recipe.ts
> -});
Any reason for an extra line

2023-08-01 15:12 UTC, RICHYDOS approved these changes

2023-08-01 23:02 UTC, RICHYDOS commented on src/core/models/recipe.ts
> +>>>>>>> origin
What is happening here?

2023-08-01 23:02 UTC, RICHYDOS commented on src/core/models/recipe.ts
> +=======
Same question as before... What is happening here

2023-08-02 05:10 UTC, hizikex commented on src/core/models/recipe.ts
> +=======
It is resolved

2023-08-02 10:41 UTC, RICHYDOS requested changes

2023-08-02 10:41 UTC, RICHYDOS commented on src/core/database/config/database.js
> +  production: {
Got no response regarding this... We already have this file in config.js and sequelize.js. This file is not needed

2023-08-02 11:14 UTC, hizikex commented on src/core/database/config/database.js
> +  production: {
It's same file... Not a new one.
It was just renamed.

2023-08-02 12:14 UTC, RICHYDOS approved these changes

2023-08-02 12:18 UTC, LucianaDera approved these changes

2023-08-02 12:21 UTC, merged