BEI-14: Register users
korapay/Foodies-Haven pull request #33
Opened 2023-08-04 17:26 UTC by hizikex

#### WHY THIS PR?
- There is need for users to register on this paltform.

#### WHAT DOES THIS PR DO?
-It allows users to register with at least their username, email and password.

HOW CAN THIS PR BE TESTED?
-By not passing a value in either of the field mentioned above, a user will not be able to register on foodies_haven.

THINGS YOU MAY WANT THE REVIEWER TO NOTE.
N/A

2023-08-04 17:56 UTC, LucianaDera requested changes

2023-08-04 17:56 UTC, LucianaDera commented on src/core/helpers/cloudinary.ts
> +
are we making use of cloudinary?

2023-08-04 18:26 UTC, RICHYDOS commented on src/core/helpers/cloudinary.ts
> +
@hizikex please respond to this

2023-08-04 18:26 UTC, RICHYDOS approved these changes

2023-08-05 07:59 UTC, LucianaDera approved these changes

2023-08-05 10:40 UTC, RICHYDOS requested changes

2023-08-05 10:40 UTC, RICHYDOS commented on src/core/repositories/User.ts
> +  }
What does this do?

2023-08-05 11:46 UTC, hizikex commented on src/core/repositories/User.ts
> +  }
Is not supposed to be here.

2023-08-05 11:50 UTC, RICHYDOS approved these changes

2023-08-05 11:50 UTC, merged