BEI-17: Get user profile
korapay/Foodies-Haven pull request #35
Opened 2023-08-06 00:48 UTC by hizikex

#### WHY THIS PR?
There is need for users to see their profile.

#### WHAT DOES THIS PR DO?
It allows users to see their profile, when they are logged in.

#### HOW CAN THIS PR BE TESTED?
Error will arise when requests is made by without token.

THINGS YOU MAY WANT THE REVIEWER TO NOTE.
N/A

2023-08-06 15:58 UTC, RICHYDOS requested changes

2023-08-06 15:58 UTC, RICHYDOS commented on src/api/Route/user.ts
> +router.get('/profile/:username', authMiddleware, getUserProfile);
This should be in its own  profile.ts file

2023-08-07 09:16 UTC, RICHYDOS requested changes

2023-08-07 09:16 UTC, RICHYDOS commented on src/core/controllers/profile.ts
> +import {Request, Response, NextFunction } from 'express';
Remove this line since it's not being used

2023-08-07 09:16 UTC, RICHYDOS commented on src/core/controllers/user.ts
> +};
Remove this method since you moved it to the profile.ts file

2023-08-07 09:16 UTC, RICHYDOS commented on src/core/interfaces/profile.ts
> -
is that an underscore?

2023-08-07 09:53 UTC, LucianaDera commented
Please attend to the comments

2023-08-07 10:40 UTC, hizikex commented on src/core/interfaces/profile.ts
> -
No

2023-08-07 12:07 UTC, RICHYDOS requested changes

2023-08-07 12:07 UTC, RICHYDOS commented on src/core/controllers/user.ts
> +};
You did not remove the getProfile controller from the file

2023-08-07 16:29 UTC, RICHYDOS approved these changes

2023-08-07 16:30 UTC, merged