Bei-39: comment on a recipe
korapay/Foodies-Haven pull request #39
Opened 2023-08-10 10:06 UTC by LucianaDera

WHY THIS PR?
We want users to have the ability to comment on different recipes.

WHAT DOES THIS PR DO?
It allows authenticated user comment on recipes.

THINGS YOU MAY WANT THE REVIEWER TO NOTE.
N/A

2023-08-10 10:22 UTC, hizikex requested changes

2023-08-10 10:22 UTC, hizikex commented on src/core/controllers/comment.ts
> +};
I feel this commentResponse is repeating what is in comment.
WHat i mean is that if you return comment, you will get same result.
That's what I feel. So you can decide sha.

2023-08-10 11:07 UTC, RICHYDOS requested changes

2023-08-10 11:07 UTC, RICHYDOS commented on src/api/Route/index.ts
> +
Firstly remove the extra spaces. Secondly based on what is in the documentation, there should be only one route here '/api/recipes' meaning there is no need for a comments route file.

2023-08-10 11:07 UTC, RICHYDOS commented on src/api/Route/comment.ts
> +export { router as commentRoutes };
Please move the contents of this file into the recipe.ts route file

2023-08-10 11:07 UTC, RICHYDOS commented on src/api/requestHandlers/comment.ts
> +};
add an extra line

2023-08-11 15:21 UTC, hizikex commented on src/core/models/comments.ts
> +      modelName: 'comments',
We were told to be using tableName here and not modelName.

2023-08-11 15:42 UTC, RICHYDOS requested changes

2023-08-11 15:42 UTC, RICHYDOS commented on src/api/Route/index.ts
> +
Remove extra line

2023-08-11 15:42 UTC, RICHYDOS commented on src/api/Route/index.ts
> +import { recipeRouter } from './recipe';
Let's keep the naming convention uniform. Why not 'recipeRoutes' instead of recipeRouter

2023-08-11 15:42 UTC, RICHYDOS commented on src/core/controllers/comment.ts
> +console.log('Retrieved Recipe:', recipe);
This line is not needed right? If it is, it's better to use our winston logger instead

2023-08-12 06:51 UTC, LucianaDera commented on src/core/models/comments.ts
> +      modelName: 'comments',
Not really, it actually thesame thing.

2023-08-12 20:22 UTC, hizikex approved these changes

2023-08-13 11:03 UTC, RICHYDOS approved these changes

2023-08-13 11:03 UTC, merged