chore: set up mysql database with sequelize ORM
korapay/Foodies-Haven pull request #4
Opened 2023-07-11 11:15 UTC by hizikex

#### WHY THIS PR?
There is need to have a database, where data can be stored, maintained and retrieved

#### WHAT DOES THIS PR DO?
It stores data, maintains it and gives access to retrieval

#### HOW CAN THIS PR BE TESTED?
N/A

#### THINGS YOU MAY WANT THE REVIEWER TO NOTE.
N/A

2023-07-11 12:14 UTC, RICHYDOS commented on src/config/config.ts
Might be better to abstract the sensitive data into a ".env" file and import from there. Then create a ".env.example" file so we know the expected values for sensitive data.

2023-07-11 12:35 UTC, hizikex commented on src/config/config.ts
I considered that too, but was just sticking with the task, because I feel it might still be in another task.
I don't know.

2023-07-11 13:07 UTC, LordUche requested changes

2023-07-11 13:07 UTC, LordUche commented on src/config/config.ts
> +export default sequelize;
Please add a new line after this
```suggestion
export default sequelize;

```

2023-07-11 13:43 UTC, LucianaDera commented
please include an .env example

2023-07-12 03:53 UTC, LordUche requested changes
Please include a `.env.example` file just like @LucianaDera suggested

2023-07-12 03:57 UTC, LordUche commented
@hizikex your PR title should also contain the Jira ticket numbers.
For instance, this PR title should be something like:

**BEI-5: Set up MySQL Database with Sequelize ORM**

2023-07-12 05:32 UTC, hizikex commented
Correction has being made to point points commented on.

2023-07-12 16:42 UTC, RICHYDOS reviewed
I'm not seeing the ".env.example" file. Did you create it in the root directory

2023-07-13 11:48 UTC, hizikex commented
Yes, I did create the .env.example in the root folder

2023-07-13 12:36 UTC, LordUche approved these changes

2023-07-13 12:42 UTC, merged