BEI-38: create a recipe
korapay/Foodies-Haven pull request #43
Opened 2023-08-11 15:18 UTC by LucianaDera

2023-08-12 20:04 UTC, hizikex requested changes

2023-08-12 20:04 UTC, hizikex commented on src/api/Route/index.ts
> +import { recipeRouter } from './recipe';
It will be nice for us to stick with a specific naming convention.
Therefore, I think recipeRouter should be changed to recipeRoutes

2023-08-12 20:04 UTC, hizikex commented on src/api/Route/index.ts
> +  router.use('/api/recipes', recipeRouter)
call the recipeRoutes here.

2023-08-13 05:46 UTC, hizikex approved these changes

2023-08-13 05:46 UTC, hizikex commented on src/api/Route/index.ts
> +  router.use('/api/recipes', recipeRouter)
this has not change from my view

2023-08-13 11:17 UTC, RICHYDOS requested changes
Nice Work. Pls implement @hizikex changes so this can be approved

2023-08-13 11:56 UTC, RICHYDOS approved these changes

2023-08-13 11:57 UTC, merged