BEI-44: Unfavourite a recipe
korapay/Foodies-Haven pull request #44
Opened 2023-08-12 23:36 UTC by LucianaDera

WHY THIS PR?
We want users to have the ability to unfavourite a recipe.

WHAT DOES THIS PR DO?
It allows authenticated user to unfavourite a recipe.

THINGS YOU MAY WANT THE REVIEWER TO NOTE.
N/A

2023-08-13 11:10 UTC, RICHYDOS requested changes

2023-08-13 11:10 UTC, RICHYDOS commented on src/core/controllers/favourite.ts
> +}
add an extra line

2023-08-13 11:25 UTC, LucianaDera commented on src/core/controllers/favourite.ts
> +}
theres an extra line

2023-08-13 12:05 UTC, RICHYDOS requested changes

2023-08-13 12:05 UTC, RICHYDOS commented on src/api/Route/favorite.ts
> +export { router as profileRoutes };
what's going on here? I don't think this file should exist

2023-08-14 07:16 UTC, hizikex approved these changes

2023-08-14 10:01 UTC, RICHYDOS requested changes

2023-08-14 10:01 UTC, RICHYDOS commented on src/api/Route/recipe.ts
> +router.delete('/:slug/favorite', authMiddleware, RequestHandler.unfavoriteHandler);
What happened to the create a comment route? Did you delete it ?

2023-08-14 10:14 UTC, RICHYDOS requested changes

2023-08-14 10:14 UTC, RICHYDOS commented on src/api/requestHandlers/comment.ts
> +}
This should not be here

2023-08-14 10:16 UTC, RICHYDOS approved these changes

2023-08-14 10:17 UTC, RICHYDOS approved these changes

2023-08-14 10:28 UTC, hizikex approved these changes

2023-08-14 10:30 UTC, merged