BEI-40: Update a recipe
korapay/Foodies-Haven pull request #45
Opened 2023-08-13 22:50 UTC by LucianaDera

WHY THIS PR?
We want users to have the ability to update created recipes.

WHAT DOES THIS PR DO?
It allows authenticated users update an existing recipe.

THINGS YOU MAY WANT THE REVIEWER TO NOTE.
N/A

2023-08-14 06:34 UTC, RICHYDOS requested changes
Nice work.

2023-08-14 06:34 UTC, RICHYDOS commented on src/core/controllers/recipe.ts
> +    };
Nice work. The only issue I have is that this doesn't return a full recipe. It only returns the recipe table. Check the documentation for what I mean

2023-08-14 06:50 UTC, hizikex requested changes

2023-08-14 06:50 UTC, hizikex commented on src/core/controllers/recipe.ts
> +    };
I agree with this

2023-08-17 12:08 UTC, LordUche requested changes

2023-08-17 12:08 UTC, LordUche commented on src/core/controllers/recipe.ts
> +    }
This is not necessary

2023-08-21 10:29 UTC, RICHYDOS approved these changes

2023-08-21 10:29 UTC, RICHYDOS commented on src/core/controllers/recipe.ts
> +    };
What if a user doesn't update the title? Is a new slug generated or nothing happens?

2023-08-22 12:43 UTC, hizikex approved these changes

2023-08-24 12:26 UTC, LordUche requested changes

2023-08-24 12:26 UTC, LordUche commented on logs/combined.log
Please ignore log files

2023-08-24 12:26 UTC, LordUche commented on src/core/controllers/recipe.ts
> +    };
All these can be done in a `beforeUpdate` hook

2023-08-24 12:26 UTC, LordUche commented on src/core/controllers/recipe.ts
> +    const { title, } = req.body;
```suggestion
    const { title, description } = req.body;
```

2023-09-25 10:22 UTC, LordUche approved these changes

2023-09-25 10:23 UTC, merged