BEE-9: Setup Hound CI for automated code reviews
korapay/Foodies-Haven pull request #5
Opened 2023-07-11 11:24 UTC by LucianaDera

WHY THIS PR?
  
  - For automated code review.
  
  WHAT DOES THIS PR DO?
  
  - For early detection of issues/bugs in this codebase.
  - It  helps maintain a consistent code structure throughout this project.
  - it improves code quality, by providing feedbacks.
  
  THINGS YOU MAY WANT THE REVIEWER TO NOTE?
  
  - First activate  the hound ci on your repository.
  - Enable ESLint style checking.

2023-07-11 11:35 UTC, LordUche requested changes

2023-07-11 11:35 UTC, LordUche commented on .eslintrc.json
The config should be in `.hound.yml`. This file is not needed.

2023-07-11 11:57 UTC, hizikex approved these changes

2023-07-11 12:19 UTC, RICHYDOS approved these changes

2023-07-12 03:51 UTC, LordUche requested changes

2023-07-12 03:51 UTC, LordUche commented on .hound.yml
> +fail_on_violations: true
Please add a new line after this

2023-07-12 10:21 UTC, LordUche approved these changes

2023-07-12 10:27 UTC, merged