BEI-47: Recipe slug
korapay/Foodies-Haven pull request #51
Opened 2023-08-20 22:39 UTC by LucianaDera

WHY THIS PR?
We want the slug to be automatically created when will define the recipe title.

WHAT DOES THIS PR DO?
When a recipe title is created it automatically becomes the slug name with a unique representation.

THINGS YOU MAY WANT THE REVIEWER TO NOTE.

2023-08-22 12:42 UTC, hizikex approved these changes

2023-08-24 11:39 UTC, LordUche requested changes

2023-08-24 11:39 UTC, LordUche commented on logs/combined.log
Please ignore log files

2023-08-24 11:39 UTC, LordUche commented on logs/error.log
Please ignore log files

2023-08-24 11:39 UTC, LordUche commented on src/core/controllers/recipe.ts
> +      slug: "",
You can remove this line

2023-08-24 12:46 UTC, LordUche requested changes

2023-08-24 12:48 UTC, LordUche approved these changes

2023-08-24 12:48 UTC, merged