BEI-6: Setup linting with Eslint
korapay/Foodies-Haven pull request #7
Opened 2023-07-12 14:30 UTC by hizikex

#### WHY THIS PR?
- There is a need identify and report common code issues, enforcing coding styles and improve code quality.

#### WHAT DOES THIS PR DO?
-  It helps to catch common code issues.
-  It helps to maintain consistent coding style.
- It improves cod readability.

HOW CAN THIS PR BE TESTED?
- Create a .eslintrc.js file in the root directory, and map {"extends": "airbnb-typescript"}

THINGS YOU MAY WANT THE REVIEWER TO NOTE.
N/A

2023-07-12 14:52 UTC, hizikex commented on .eslintrc.js
> +  };
Thanks.

2023-07-12 15:25 UTC, LucianaDera approved these changes

2023-07-12 16:46 UTC, RICHYDOS approved these changes

2023-07-12 17:15 UTC, LordUche requested changes

2023-07-12 17:15 UTC, LordUche commented on .eslintrc.js
> +
```suggestion
  };

```
There seems to be some extra space. Kindly take them out.

2023-07-12 17:22 UTC, LordUche commented
@hizikex Hound CI is complaining about the eslintrc file format. Apparently, it only supports JSON and Yaml. You can change it to a JSON file by renaming it to `.eslintrc.json` or `.eslintrc` and then changing the contents of the file to JSON instead of JavaScript.

Also, remember to update the `.hound.yml` file to point to the correct eslintrc file.

2023-07-13 11:10 UTC, LordUche requested changes

2023-07-13 11:10 UTC, LordUche commented on .eslintrc.json
> +        "ecmaVersion": "latest"
```suggestion
        "ecmaVersion": "latest",
        "sourceType": "module"
```

2023-07-13 11:34 UTC, hizikex commented on .eslintrc.json
> +        "ecmaVersion": "latest"
This has been done.

2023-07-13 11:45 UTC, LordUche approved these changes

2023-07-13 11:47 UTC, merged